---
- name: Oracle DELETE Operation
  hosts: 3.110.62.109
  gather_facts: false
  vars:
    ansible_user: ubuntu

  tasks:
    - name: Create DELETE SQL file
      copy:
        dest: /tmp/delete_customer.sql
        content: |
          DELETE FROM customers 
          WHERE customer_name = 'RIA_TestUser';
          COMMIT;
          EXIT;

    - name: Copy SQL file into container
      command: docker cp /tmp/delete_customer.sql oracle-xe:/tmp/delete_customer.sql

    - name: Execute DELETE statement
      command: docker exec oracle-xe sqlplus -S appuser/Azalio123456@XEPDB1 @/tmp/delete_customer.sql
      register: sql_result

    - name: Show result
      debug:
        var: sql_result.stdout_lines
